import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";
import { sanityClient, urlFor } from "../sanity";
import { Collection } from "../typings";

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {
  collections: Collection[];
}

const Home = ({ collections }: HomeProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="w-52 cursor-pointer text-xl font-extralight sm:w-80">
        The{" "}
        <span className="font-extrabold underline decoration-pink-600/50">
          PAPAFAM
        </span>{" "}
        NFT Market Place
      </h1>

      <main className={styles.main}>
        <div>
          {collections.map((collection) => (
            <>
              <div>
                <img
                  className="h-96 w-60 rounded-2xl object-cover"
                  src={urlFor(collection.mainImage).url()}
                  alt=""
                />

                <div>
                  <h2 className="text-3xl">{collection.title}</h2>
                  <p className="mt-2 text-sm text-gray-400">
                    {collection.description}
                  </p>
                </div>
              </div>
            </>
          ))}
        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const query = `*[_type == "collection"]{
    _id,
      title,
      address,
      description,
      mainImage {
      asset
      },
    slug {
      current
    },
    creator-> {
      _id,
      name,
      address,
      slug {
        current
      }
    }
    
  }
  `;

  const collections = await sanityClient.fetch(query);
  console.log("collections", collections);

  return {
    props: {
      collections,
    },
  };
};

export default Home;
